#!/bin/sh
echo "colortest" | figlet
for i in $(seq 1 255); do
  tput setaf "$i"
  a=$(($i % 4))
  case "$a" in
    0|1|2)
      printf "$i: hallo \t"
    ;;
    3)
      printf "$i: hallo \t\n"
    ;;
  esac
done

