#!/bin/sh

usage () {
  echo "$0 [--enable|--disable]"
}

case "$1" in
  --enable)
    defaults write com.apple.finder CreateDesktop -bool false
    killall Finder
  ;;
  --disable)
    defaults write com.apple.finder CreateDesktop -bool true
    killall Finder
  ;;
  --help)
    usage
    exit 0
  ;;
  *)
    echo "Usage error."
    usage
    exit 255
  ;;
esac

