#!/bin/bash

echo "Firefox (Dockerized): Committing last changes..."

latesttag="$(docker images | grep '^firefox-dockerized' | head -n 1 | awk '{printf $2}')"
major="$(echo "$latesttag" | cut -d"." -f 1)"
minor="$(echo "$latesttag" | cut -d"." -f 2)"
let minor+=1
newtag="${major}.${minor}"
id="$(docker ps | grep 'firefox-dockerized' | head -n 1 | xargs | cut -d" " -f 1)"
a="$(docker commit $id)"; docker tag "$a" "firefox-dockerized:${newtag}"

echo "Firefox (Dockerized): Done."
echo 
r="$(docker images | grep '^firefox-dockerized' | head -n 1 | awk '{printf $2}')"
echo "Revision: $r"


