#!/bin/bash
# 
# hidden - easily enable/disable display of hidden files in Mac OS X
# Copyright (c) 2015 Armin Jenewein <armin@mutt.email>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
 
name="${0##*/}"
version="0.1"

echo "$name"

exit 0

usage () {
  echo "--- $0 - Enable/Disable display of hidden files in Mac OS X Finder.app "
  echo "--- Usage: $0 <on|off|help>"
}

case $1 in
  on)
    echo -n "--- Enabling display of hidden files in Finder..."
    /usr/bin/defaults write com.apple.finder AppleShowAllFiles TRUE
    echo "done."
    echo -n "--- Restarting Finder..."
    killall Finder
    echo "done."
  ;;
  off)
    echo -n "--- Disabling display of hidden files in Finder..."
    /usr/bin/defaults write com.apple.finder AppleShowAllFiles FALSE
    echo "done."
    echo -n "--- Restarting Finder..."
    killall Finder
    echo "done."
  ;;
  help|*)
    usage
  ;;
esac


