#!/bin/bash

# simply prints ~/.ssh/known_hosts but omits a specific line

usage () {
  echo "$0 <linenumber>"
}

if [[ $# -lt 1 ]]; then
  usage
  exit 255
fi

o="$1"; i=0; cat $HOME/.ssh/known_hosts | while read line; do let i+=1; if [[ ! "$i" -eq "$o" ]]; then echo "$line"; fi; done



