#!/bin/bash

# .:. retina .:.
# Dynamically switches the screen resolution on a Macbook with Retina Display.
# Usage:  retina N  (N = integer)
# Requires "screenresolution" by jhford => https://github.com/jhford/screenresolution.git

modes=(2560x1600x32@0 2048x1280x32@0 1650x1050x32@0 1280x800x32@0 1152x720x32@0)

res () {
  echo "Setting display mode: ${modes[$1]}"
  screenresolution set "${modes[$1]}"
}

usage () {
  echo "Usage: ${0##*/} [1-5]"
  exit 1
}

case $1 in
  1)
    res 0
  ;;
  2)
    res 1
  ;;
  3)
    res 2
  ;;
  4)
    res 3
  ;;
  5)
    res 4
  ;;
  *)
    usage
esac


