#!/bin/bash

# tfr - type friendly renamer

for i in *; do new="$(echo "$i" | tr '[:upper:]' '[:lower:]' | tr ' ' '_' | tr '_' '.' | sed 's/\]\[/./' | sed 's/\.\././g' | sed 's/\[//g;s/\]//g')"; echo "old: $i"; echo "new: $new"; echo; done


