#!/usr/bin/env python

# 
# wifiscan - released under the terms of the WTFPL.
#
# outputs a list of currently visible wifi access points under FreeBSD 10.3
# 

from subprocess import Popen, PIPE

proc = Popen(['ifconfig', '-v', 'wlan0', 'scan'], stdout=PIPE)

for line in proc.stdout:
  print line[0:33].strip()






